/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import com.mysql.jdbc.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

import java.sql.PreparedStatement;
import conexionescuela.conexionsql;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class formulario1 extends javax.swing.JFrame {
    
    conexionsql  con= new conexionsql();
    Connection CON=con.conexion();

    /**
     * Creates new form formulario1
     */
    public formulario1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrardatos();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tx_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_apellido = new javax.swing.JTextField();
        txtmateria = new javax.swing.JComboBox<>();
        tx_calificacion = new javax.swing.JTextField();
        txtestatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btmupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbalumnos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel5.setText("NOMBRE");

        jLabel6.setText("APELLIDO");

        tx_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_apellidoActionPerformed(evt);
            }
        });

        txtmateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematicas", "español", "ingles", "sociales" }));
        txtmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmateriaActionPerformed(evt);
            }
        });

        tx_calificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_calificacionActionPerformed(evt);
            }
        });

        txtestatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aprobado", "reprobado" }));

        jLabel1.setText("MATERIA");

        jLabel2.setText("CALIFICACION");

        jLabel3.setText("ESTATUS");

        btnagregar.setText("Nuevo");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btmupdate.setText("Actulizar");
        btmupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtestatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tx_calificacion)
                            .addComponent(txtmateria, 0, 184, Short.MAX_VALUE)
                            .addComponent(tx_nombre)
                            .addComponent(tx_apellido)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnagregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmupdate)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tx_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addComponent(tx_calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar)
                    .addComponent(btnguardar)
                    .addComponent(btneliminar)
                    .addComponent(btmupdate))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        tbalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbalumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbalumnos);

        jLabel4.setText("BUSQUEDA");

        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmateriaActionPerformed

    private void tx_calificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_calificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_calificacionActionPerformed

    private void tx_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_apellidoActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
      eliminardatos();
      mostrardatos();
      limpiarcajas();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btmupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmupdateActionPerformed
       actualizarDatos();
       limpiarcajas();
       mostrardatos();
    }//GEN-LAST:event_btmupdateActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       // se coloca el metodo para para insertar datos
        insertarDatos();
        limpiarcajas();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
       // se coloca el metodo para para insertar datos
       limpiarcajas();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void tbalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbalumnosMouseClicked
       //metodo para seleccionar la fila d ela tabala que se quiere editar
        int filaseleccionada=tbalumnos.rowAtPoint(evt.getPoint());
        tx_nombre.setText(tbalumnos.getValueAt(filaseleccionada,1).toString());
        tx_apellido.setText(tbalumnos.getValueAt(filaseleccionada,2).toString());
        txtmateria.setSelectedItem(tbalumnos.getValueAt(filaseleccionada,3).toString());
        tx_calificacion.setText(tbalumnos.getValueAt(filaseleccionada,4).toString());
        txtestatus.setSelectedItem(tbalumnos.getValueAt(filaseleccionada,5).toString());
        

    }//GEN-LAST:event_tbalumnosMouseClicked

    private void txtbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyReleased
        filtrardatos(txtbusqueda.getText());
    }//GEN-LAST:event_txtbusquedaKeyReleased
    
    public void eliminardatos(){
            
      int filaseleccionada=tbalumnos.getSelectedRow();
      
        try {
            String sql="delete from alumnos where idalumnos="+tbalumnos.getValueAt(filaseleccionada, 0);
            Statement st=CON.createStatement();
            int n=st.executeUpdate(sql);
            
            if (n>=0){ //ciclo para detyermianr si la sentecia se ejecuta
                JOptionPane.showMessageDialog(null,"eliminacion exitosa");
            }
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"eliminacion fallida"+ e.getMessage());
        }

     
    }
    
    
    public void mostrardatos(){
        String[] titulos={"iD","Nombre","Apellido","Materia","Calificacion","Status"};
        String[] registro= new String[7]; 
        
        DefaultTableModel  modelo=new DefaultTableModel(null,titulos);
        String SQL="select * from alumnos";
        
        try{
        Statement st=CON.createStatement();
        ResultSet rs=st.executeQuery(SQL);
        
        while(rs.next()){
        registro[0]=rs.getString("idalumnos");
        registro[1]=rs.getString("nombre");
        registro[2]=rs.getString("apellido");
        registro[3]=rs.getString("materia");
        registro[4]=rs.getString("calificacion");
        registro[5]=rs.getString("estatus");

        modelo.addRow(registro);}
         
         tbalumnos.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"error al mostar datos"+e.getMessage());
        }
        
     } 
    //metodo para mostar datos filtrados por un dato de la tabla
      public void filtrardatos(String valor){
        String[] titulos={"iD","Nombre","Apellido","Materia","Calificacion","Status"};
        String[] registro= new String[7]; 
        
        DefaultTableModel  modelo=new DefaultTableModel(null,titulos);
        String SQL="select * from alumnos where nombre like '%"+valor+"%'";
        
        try{
        Statement st=CON.createStatement();
        ResultSet rs=st.executeQuery(SQL);
        
        while(rs.next()){
        registro[0]=rs.getString("idalumnos");
        registro[1]=rs.getString("nombre");
        registro[2]=rs.getString("apellido");
        registro[3]=rs.getString("materia");
        registro[4]=rs.getString("calificacion");
        registro[5]=rs.getString("estatus");

        modelo.addRow(registro);}
         
         tbalumnos.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"error al mostar datos"+e.getMessage());
        }
        
     } 
    
     public void actualizarDatos(){
        try {
            String sql=("update alumnos set nombre=?,apellido=?,materia=?,calificacion=?,estatus=? where idalumnos=?"); 
            
            int filaseleccioanda=tbalumnos.getSelectedRow();
            String dao=(String)tbalumnos.getValueAt(filaseleccioanda,0);  //PARA INDICAR LA LINEA SELECCIONADA
            PreparedStatement pt=CON.prepareStatement(sql);
            pt.setString(1,tx_nombre.getText());
            pt.setString(2,tx_apellido.getText());
            
            int seleccionar=txtmateria.getSelectedIndex();
            pt.setString(3,txtmateria.getItemAt(seleccionar));
            
            pt.setDouble(4,Double.parseDouble(tx_calificacion.getText()));
            int seleccionar2=txtestatus.getSelectedIndex();
            pt.setString(5,txtestatus.getItemAt(seleccionar2));
            
            pt.setString(6,dao);
            pt.execute();
            
            JOptionPane.showMessageDialog(null,"Actualizacion exitoso");

        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Actualizacion fallido"+ e.getMessage());
        }
    }
    
    
    
    
    
    
    
    public void limpiarcajas(){
         tx_nombre.setText("");
         tx_apellido.setText("");
         tx_calificacion.setText("");
         txtmateria.setSelectedItem(null);
     txtestatus.setSelectedItem(null);


     }
    
    
    public void insertarDatos(){
        try {
            String sql=("insert into alumnos (nombre,apellido,materia,calificacion,estatus) values(?,?,?,?,?)"); 
            PreparedStatement pt=CON.prepareStatement(sql);
            pt.setString(1,tx_nombre.getText());
            pt.setString(2,tx_apellido.getText());
            
            int seleccionar=txtmateria.getSelectedIndex();
            pt.setString(3,txtmateria.getItemAt(seleccionar));
            
            pt.setDouble(4,Double.parseDouble(tx_calificacion.getText()));
            
            int seleccionar2=txtestatus.getSelectedIndex();
            pt.setString(5,txtestatus.getItemAt(seleccionar2));
            pt.execute();
            
            JOptionPane.showMessageDialog(null,"registro exitoso");

        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,"registro fallido"+ e.getMessage());
        }
        
    }       
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmupdate;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbalumnos;
    private javax.swing.JTextField tx_apellido;
    private javax.swing.JTextField tx_calificacion;
    private javax.swing.JTextField tx_nombre;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JComboBox<String> txtestatus;
    private javax.swing.JComboBox<String> txtmateria;
    // End of variables declaration//GEN-END:variables
}
